{"name": "test_accept_order_with_wrong_id", "status": "passed", "steps": [{"name": "Принятие заказа. Если передать неверный id курьера, то вернется ошибка", "status": "passed", "steps": [{"name": "Создание одного заказа", "status": "passed", "start": 1749547357860, "stop": 1749547357860}], "start": 1749547357859, "stop": 1749547358947}], "start": 1749547357859, "stop": 1749547358948, "uuid": "acb877a7-6d86-4963-b564-296f0145ab7a", "historyId": "40331d6ca66461519555e48662729a13", "testCaseId": "40331d6ca66461519555e48662729a13", "fullName": "Test.Order.test_accept_order.TestAcceptOrder#test_accept_order_with_wrong_id", "labels": [{"name": "parentSuite", "value": "Test.Order"}, {"name": "suite", "value": "test_accept_order"}, {"name": "subSuite", "value": "TestAcceptOrder"}, {"name": "host", "value": "MacBook-Pro.local"}, {"name": "thread", "value": "45635-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Test.Order.test_accept_order"}]}