{"name": "Принятие заказа. Если передать неверный id курьера, то вернется ошибка", "status": "passed", "steps": [{"name": "Создание одного заказа", "status": "passed", "start": 1749721954302, "stop": 1749721954302}], "start": 1749721954302, "stop": 1749721955551, "uuid": "655c1b36-bbf6-4e07-aa34-e524e58fd576", "historyId": "a74293ce9f52b2c6fe56fadfbdc3db85", "testCaseId": "a74293ce9f52b2c6fe56fadfbdc3db85", "fullName": "tests.Order.test_accept_order.TestAcceptOrder#test_accept_order_with_wrong_id", "labels": [{"name": "feature", "value": "Принятие заказа"}, {"name": "parentSuite", "value": "tests.Order"}, {"name": "suite", "value": "test_accept_order"}, {"name": "subSuite", "value": "TestAcceptOrder"}, {"name": "host", "value": "MacBook-Pro.local"}, {"name": "thread", "value": "76481-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.Order.test_accept_order"}]}